apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  token: UnJXQTU0TVJ1QjcyNkU3TDdLSEZ6SmVMOXVEcUpHT0ViVWpvSzlndGVUY3pYZEctbkJpc1F5bXJPMUFYVTZLOXZUR3Q2N1JycW4xWF95cHNxMjVWZ1E9PQ==
